#!/usr/bin/env python3

import os
import sys
import pathlib
import requests

words_url = "https://raw.githubusercontent.com/bitcoin/bips/master/bip-0039/english.txt"
script_dir = pathlib.Path(__file__).parent.absolute()
destination_file = os.path.join(script_dir, "..", "bip39_words.h")


def main():
    response = requests.get(words_url)
    if response.status_code != 200:
        print("Failed to download BIP39 word list")
        sys.exit(1)

    words = response.text.strip().splitlines()
    if len(words) != 2048:
        print("Invalid word list length")
        sys.exit(1)

    with open(destination_file, "w") as f:
        f.write("/*  This file was generated by helpers/%s\n" %
                os.path.basename(__file__))
        f.write("    Downloaded from %s\n" % words_url)
        f.write("    DO NOT EDIT MANUALLY */\n")
        f.write("// clang-format off\n\n")

        f.write("#pragma once\n")
        f.write("#define BIP39_NUMBER_OF_WORDS 2048\n\n")
        f.write("const char* BIP39_WORDS[BIP39_NUMBER_OF_WORDS] = {\n")
        for word in words[:-1]:
            f.write('    "%s",\n' % word)
        f.write('    "%s"\n' % words[-1])
        f.write("};\n")
        print("Saving file to %s" % destination_file)


if __name__ == "__main__":
    main()
