#!/usr/bin/env python3

import os
import pathlib
import sys

import requests

words_url = "https://raw.githubusercontent.com/bitcoin/bips/master/bip-0039/english.txt"
script_dir = pathlib.Path(__file__).parent.absolute()
cfile_name = "bip39_words"
destination_file_h = os.path.join(script_dir, "..", f"{cfile_name}.h")
destination_file_c = os.path.join(script_dir, "..", f"{cfile_name}.c")


def main():
    response = requests.get(words_url)
    if response.status_code != 200:
        print("Failed to download BIP39 word list")
        sys.exit(1)

    words = response.text.strip().splitlines()
    if len(words) != 2048:
        print("Invalid word list length")
        sys.exit(1)

    with open(destination_file_h, "w") as f:
        f.write("/*  This file was generated by helpers/%s\n" %
                os.path.basename(__file__))
        f.write("    DO NOT EDIT MANUALLY */\n")
        f.write("#pragma once\n\n")
        f.write("#define BIP39_NUMBER_OF_WORDS 2048\n\n")
        f.write("void bip39_word_at_index(char* dest_str, unsigned int index);\n")
        print("Saving file to %s" % destination_file_h)

    with open(destination_file_c, "w") as f:
        f.write("/*  This file was generated by helpers/%s\n" %
                os.path.basename(__file__))
        f.write("    Downloaded from %s\n" % words_url)
        f.write("    DO NOT EDIT MANUALLY */\n")
        f.write("// clang-format off\n\n")

        f.write(f"#include \"{cfile_name}.h\"\n")
        f.write(f"#include <stdlib.h>\n")
        f.write(f"#include <string.h>\n\n")

        f.write("const char* BIP39_WORDS[BIP39_NUMBER_OF_WORDS] = {\n")
        for word in words[:-1]:
            f.write('  "%s",\n' % word)
        f.write('    "%s"\n' % words[-1])
        f.write("};\n\n")
        f.write(
            "void bip39_word_at_index(char* dest_str, unsigned int index){\n")
        f.write("  if (index >= BIP39_NUMBER_OF_WORDS) {\n")
        f.write("    dest_str[0] = '\\0';\n")
        f.write("  } else {\n")
        f.write("    strcpy(dest_str, BIP39_WORDS[index]);\n")
        f.write("  }\n")
        f.write("  return;\n")
        f.write("}\n")
        print("Saving file to %s" % destination_file_c)


if __name__ == "__main__":
    main()
