/*  This file was generated by helpers/bip39_test_vectors.py
    DO NOT EDIT MANUALLY */
#ifndef HPWG_BIP39_TEST_VECTORS_H
#define HPWG_BIP39_TEST_VECTORS_H

#ifdef __cplusplus
extern "C" {
#endif

#define BIP39_VECTOR_COUNT 24

int vectorEntropyBytesLengthAtIndex(unsigned int index);
int vectorEntropyBitsAtIndex(unsigned int index);
void vectorEntropyStrAtIndex(char *dest_str, unsigned int index);
void vectorEntropyAtIndex(unsigned char *dest_bytes, unsigned int index);
int vectorWordsCountAtIndex(unsigned int index);
void vectorWordAtIndex(char *dest_str, unsigned int inde, unsigned int word_numx);
void vectorSeedAtIndex(char *dest_str, unsigned int index);
void vectorXprvAtIndex(char *dest_str, unsigned int index);

#ifdef __cplusplus
} // extern "C"
#endif

#endif // HPWG_BIP39_TEST_VECTORS_H
