/*  This file was generated by helpers/bip39_words.py
    DO NOT EDIT MANUALLY */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef BIP39_WORDS_H
#define BIP39_WORDS_H

#define BIP39_NUMBER_OF_WORDS 2048

void bip39_word_at_index(char* dest_str, unsigned int index);

#endif

#ifdef __cplusplus
} // extern "C"
#endif
