/*This file was generated by helpers/bip39_words.py
    DO NOT EDIT MANUALLY */
#ifndef HPWG_BIP39_WORDS_H
#define HPWG_BIP39_WORDS_H

#ifdef __cplusplus
extern "C" {
#endif

#define BIP39_NUMBER_OF_WORDS 2048

void bip39_word_at_index(char* dest_str, unsigned int index);

#ifdef __cplusplus
} // extern "C"
#endif

#endif // HPWG_BIP39_WORDS_H
